//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace Services.RioEduca {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoginWSSoap", Namespace="http://tempuri.org")]
    public partial class LoginWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Validation validationValueField;
        
        private System.Threading.SendOrPostCallback CriarAlunoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CriarProfessorOperationCompleted;
        
        private System.Threading.SendOrPostCallback CriarFuncionarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExisteContaEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarSenhaContaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AceitarTermosOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirPerguntaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarPerguntaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetaSenhaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlteraSenhaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LoginWS() {
            this.Url = global::Services.Properties.Settings.Default.Services_RioEduca_LoginWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Validation ValidationValue {
            get {
                return this.validationValueField;
            }
            set {
                this.validationValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CriarAlunoCompletedEventHandler CriarAlunoCompleted;
        
        /// <remarks/>
        public event CriarProfessorCompletedEventHandler CriarProfessorCompleted;
        
        /// <remarks/>
        public event CriarFuncionarioCompletedEventHandler CriarFuncionarioCompleted;
        
        /// <remarks/>
        public event ExisteContaEmailCompletedEventHandler ExisteContaEmailCompleted;
        
        /// <remarks/>
        public event AlterarSenhaContaCompletedEventHandler AlterarSenhaContaCompleted;
        
        /// <remarks/>
        public event AceitarTermosCompletedEventHandler AceitarTermosCompleted;
        
        /// <remarks/>
        public event InserirPerguntaCompletedEventHandler InserirPerguntaCompleted;
        
        /// <remarks/>
        public event AlterarPerguntaCompletedEventHandler AlterarPerguntaCompleted;
        
        /// <remarks/>
        public event ResetaSenhaCompletedEventHandler ResetaSenhaCompleted;
        
        /// <remarks/>
        public event AlteraSenhaCompletedEventHandler AlteraSenhaCompleted;
        
        /// <remarks/>
        public event ValidaUsuarioCompletedEventHandler ValidaUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ValidationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CriarAluno", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Aluno CriarAluno(string nome, string matricula, string escola, string turma, string serie) {
            object[] results = this.Invoke("CriarAluno", new object[] {
                        nome,
                        matricula,
                        escola,
                        turma,
                        serie});
            return ((Aluno)(results[0]));
        }
        
        /// <remarks/>
        public void CriarAlunoAsync(string nome, string matricula, string escola, string turma, string serie) {
            this.CriarAlunoAsync(nome, matricula, escola, turma, serie, null);
        }
        
        /// <remarks/>
        public void CriarAlunoAsync(string nome, string matricula, string escola, string turma, string serie, object userState) {
            if ((this.CriarAlunoOperationCompleted == null)) {
                this.CriarAlunoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCriarAlunoOperationCompleted);
            }
            this.InvokeAsync("CriarAluno", new object[] {
                        nome,
                        matricula,
                        escola,
                        turma,
                        serie}, this.CriarAlunoOperationCompleted, userState);
        }
        
        private void OnCriarAlunoOperationCompleted(object arg) {
            if ((this.CriarAlunoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CriarAlunoCompleted(this, new CriarAlunoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ValidationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CriarProfessor", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Professor CriarProfessor(string nome, string matricula, string escola, string turma, string serie, string CPF, string Disciplina) {
            object[] results = this.Invoke("CriarProfessor", new object[] {
                        nome,
                        matricula,
                        escola,
                        turma,
                        serie,
                        CPF,
                        Disciplina});
            return ((Professor)(results[0]));
        }
        
        /// <remarks/>
        public void CriarProfessorAsync(string nome, string matricula, string escola, string turma, string serie, string CPF, string Disciplina) {
            this.CriarProfessorAsync(nome, matricula, escola, turma, serie, CPF, Disciplina, null);
        }
        
        /// <remarks/>
        public void CriarProfessorAsync(string nome, string matricula, string escola, string turma, string serie, string CPF, string Disciplina, object userState) {
            if ((this.CriarProfessorOperationCompleted == null)) {
                this.CriarProfessorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCriarProfessorOperationCompleted);
            }
            this.InvokeAsync("CriarProfessor", new object[] {
                        nome,
                        matricula,
                        escola,
                        turma,
                        serie,
                        CPF,
                        Disciplina}, this.CriarProfessorOperationCompleted, userState);
        }
        
        private void OnCriarProfessorOperationCompleted(object arg) {
            if ((this.CriarProfessorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CriarProfessorCompleted(this, new CriarProfessorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ValidationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CriarFuncionario", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Funcionario CriarFuncionario(string nome, string CPF, string cargo, string funcao, string setor) {
            object[] results = this.Invoke("CriarFuncionario", new object[] {
                        nome,
                        CPF,
                        cargo,
                        funcao,
                        setor});
            return ((Funcionario)(results[0]));
        }
        
        /// <remarks/>
        public void CriarFuncionarioAsync(string nome, string CPF, string cargo, string funcao, string setor) {
            this.CriarFuncionarioAsync(nome, CPF, cargo, funcao, setor, null);
        }
        
        /// <remarks/>
        public void CriarFuncionarioAsync(string nome, string CPF, string cargo, string funcao, string setor, object userState) {
            if ((this.CriarFuncionarioOperationCompleted == null)) {
                this.CriarFuncionarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCriarFuncionarioOperationCompleted);
            }
            this.InvokeAsync("CriarFuncionario", new object[] {
                        nome,
                        CPF,
                        cargo,
                        funcao,
                        setor}, this.CriarFuncionarioOperationCompleted, userState);
        }
        
        private void OnCriarFuncionarioOperationCompleted(object arg) {
            if ((this.CriarFuncionarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CriarFuncionarioCompleted(this, new CriarFuncionarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ValidationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExisteContaEmail", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Conta ExisteContaEmail(string email) {
            object[] results = this.Invoke("ExisteContaEmail", new object[] {
                        email});
            return ((Conta)(results[0]));
        }
        
        /// <remarks/>
        public void ExisteContaEmailAsync(string email) {
            this.ExisteContaEmailAsync(email, null);
        }
        
        /// <remarks/>
        public void ExisteContaEmailAsync(string email, object userState) {
            if ((this.ExisteContaEmailOperationCompleted == null)) {
                this.ExisteContaEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteContaEmailOperationCompleted);
            }
            this.InvokeAsync("ExisteContaEmail", new object[] {
                        email}, this.ExisteContaEmailOperationCompleted, userState);
        }
        
        private void OnExisteContaEmailOperationCompleted(object arg) {
            if ((this.ExisteContaEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteContaEmailCompleted(this, new ExisteContaEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ValidationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarSenhaConta", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Senha AlterarSenhaConta(string email, string senha, string ativo) {
            object[] results = this.Invoke("AlterarSenhaConta", new object[] {
                        email,
                        senha,
                        ativo});
            return ((Senha)(results[0]));
        }
        
        /// <remarks/>
        public void AlterarSenhaContaAsync(string email, string senha, string ativo) {
            this.AlterarSenhaContaAsync(email, senha, ativo, null);
        }
        
        /// <remarks/>
        public void AlterarSenhaContaAsync(string email, string senha, string ativo, object userState) {
            if ((this.AlterarSenhaContaOperationCompleted == null)) {
                this.AlterarSenhaContaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarSenhaContaOperationCompleted);
            }
            this.InvokeAsync("AlterarSenhaConta", new object[] {
                        email,
                        senha,
                        ativo}, this.AlterarSenhaContaOperationCompleted, userState);
        }
        
        private void OnAlterarSenhaContaOperationCompleted(object arg) {
            if ((this.AlterarSenhaContaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarSenhaContaCompleted(this, new AlterarSenhaContaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ValidationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AceitarTermos", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AceitarTermos(string email, bool aceito) {
            object[] results = this.Invoke("AceitarTermos", new object[] {
                        email,
                        aceito});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AceitarTermosAsync(string email, bool aceito) {
            this.AceitarTermosAsync(email, aceito, null);
        }
        
        /// <remarks/>
        public void AceitarTermosAsync(string email, bool aceito, object userState) {
            if ((this.AceitarTermosOperationCompleted == null)) {
                this.AceitarTermosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAceitarTermosOperationCompleted);
            }
            this.InvokeAsync("AceitarTermos", new object[] {
                        email,
                        aceito}, this.AceitarTermosOperationCompleted, userState);
        }
        
        private void OnAceitarTermosOperationCompleted(object arg) {
            if ((this.AceitarTermosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AceitarTermosCompleted(this, new AceitarTermosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ValidationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InserirPergunta", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InserirPergunta(string email, string pergunta, string resposta) {
            object[] results = this.Invoke("InserirPergunta", new object[] {
                        email,
                        pergunta,
                        resposta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InserirPerguntaAsync(string email, string pergunta, string resposta) {
            this.InserirPerguntaAsync(email, pergunta, resposta, null);
        }
        
        /// <remarks/>
        public void InserirPerguntaAsync(string email, string pergunta, string resposta, object userState) {
            if ((this.InserirPerguntaOperationCompleted == null)) {
                this.InserirPerguntaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirPerguntaOperationCompleted);
            }
            this.InvokeAsync("InserirPergunta", new object[] {
                        email,
                        pergunta,
                        resposta}, this.InserirPerguntaOperationCompleted, userState);
        }
        
        private void OnInserirPerguntaOperationCompleted(object arg) {
            if ((this.InserirPerguntaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirPerguntaCompleted(this, new InserirPerguntaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ValidationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarPergunta", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AlterarPergunta(string email, string senha, string pergunta, string resposta) {
            object[] results = this.Invoke("AlterarPergunta", new object[] {
                        email,
                        senha,
                        pergunta,
                        resposta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AlterarPerguntaAsync(string email, string senha, string pergunta, string resposta) {
            this.AlterarPerguntaAsync(email, senha, pergunta, resposta, null);
        }
        
        /// <remarks/>
        public void AlterarPerguntaAsync(string email, string senha, string pergunta, string resposta, object userState) {
            if ((this.AlterarPerguntaOperationCompleted == null)) {
                this.AlterarPerguntaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarPerguntaOperationCompleted);
            }
            this.InvokeAsync("AlterarPergunta", new object[] {
                        email,
                        senha,
                        pergunta,
                        resposta}, this.AlterarPerguntaOperationCompleted, userState);
        }
        
        private void OnAlterarPerguntaOperationCompleted(object arg) {
            if ((this.AlterarPerguntaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarPerguntaCompleted(this, new AlterarPerguntaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ValidationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetaSenha", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ResetaSenha(string email, string pergunta, string resposta) {
            object[] results = this.Invoke("ResetaSenha", new object[] {
                        email,
                        pergunta,
                        resposta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ResetaSenhaAsync(string email, string pergunta, string resposta) {
            this.ResetaSenhaAsync(email, pergunta, resposta, null);
        }
        
        /// <remarks/>
        public void ResetaSenhaAsync(string email, string pergunta, string resposta, object userState) {
            if ((this.ResetaSenhaOperationCompleted == null)) {
                this.ResetaSenhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetaSenhaOperationCompleted);
            }
            this.InvokeAsync("ResetaSenha", new object[] {
                        email,
                        pergunta,
                        resposta}, this.ResetaSenhaOperationCompleted, userState);
        }
        
        private void OnResetaSenhaOperationCompleted(object arg) {
            if ((this.ResetaSenhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetaSenhaCompleted(this, new ResetaSenhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ValidationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlteraSenha", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AlteraSenha(string email, string senha, string novasenha) {
            object[] results = this.Invoke("AlteraSenha", new object[] {
                        email,
                        senha,
                        novasenha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AlteraSenhaAsync(string email, string senha, string novasenha) {
            this.AlteraSenhaAsync(email, senha, novasenha, null);
        }
        
        /// <remarks/>
        public void AlteraSenhaAsync(string email, string senha, string novasenha, object userState) {
            if ((this.AlteraSenhaOperationCompleted == null)) {
                this.AlteraSenhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlteraSenhaOperationCompleted);
            }
            this.InvokeAsync("AlteraSenha", new object[] {
                        email,
                        senha,
                        novasenha}, this.AlteraSenhaOperationCompleted, userState);
        }
        
        private void OnAlteraSenhaOperationCompleted(object arg) {
            if ((this.AlteraSenhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlteraSenhaCompleted(this, new AlteraSenhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ValidationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidaUsuario", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidaUsuario(string email, string senha) {
            object[] results = this.Invoke("ValidaUsuario", new object[] {
                        email,
                        senha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaUsuarioAsync(string email, string senha) {
            this.ValidaUsuarioAsync(email, senha, null);
        }
        
        /// <remarks/>
        public void ValidaUsuarioAsync(string email, string senha, object userState) {
            if ((this.ValidaUsuarioOperationCompleted == null)) {
                this.ValidaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaUsuarioOperationCompleted);
            }
            this.InvokeAsync("ValidaUsuario", new object[] {
                        email,
                        senha}, this.ValidaUsuarioOperationCompleted, userState);
        }
        
        private void OnValidaUsuarioOperationCompleted(object arg) {
            if ((this.ValidaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaUsuarioCompleted(this, new ValidaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org", IsNullable=false)]
    public partial class Validation : System.Web.Services.Protocols.SoapHeader {
        
        private string authTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string AuthToken {
            get {
                return this.authTokenField;
            }
            set {
                this.authTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class Senha {
        
        private string senhaField;
        
        private string ativoField;
        
        private string statusField;
        
        private string msgErroField;
        
        /// <remarks/>
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public string ativo {
            get {
                return this.ativoField;
            }
            set {
                this.ativoField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string msgErro {
            get {
                return this.msgErroField;
            }
            set {
                this.msgErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class Conta {
        
        private string emailField;
        
        private string senhaField;
        
        private string statusField;
        
        private string msgErroField;
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string msgErro {
            get {
                return this.msgErroField;
            }
            set {
                this.msgErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class Funcionario {
        
        private string emailField;
        
        private string senhaField;
        
        private string statusField;
        
        private string msgErroField;
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string msgErro {
            get {
                return this.msgErroField;
            }
            set {
                this.msgErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class Professor {
        
        private string emailField;
        
        private string senhaField;
        
        private string statusField;
        
        private string msgErroField;
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string msgErro {
            get {
                return this.msgErroField;
            }
            set {
                this.msgErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class Aluno {
        
        private string emailField;
        
        private string senhaField;
        
        private string statusField;
        
        private string msgErroField;
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string msgErro {
            get {
                return this.msgErroField;
            }
            set {
                this.msgErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CriarAlunoCompletedEventHandler(object sender, CriarAlunoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CriarAlunoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CriarAlunoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Aluno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Aluno)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CriarProfessorCompletedEventHandler(object sender, CriarProfessorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CriarProfessorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CriarProfessorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Professor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Professor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CriarFuncionarioCompletedEventHandler(object sender, CriarFuncionarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CriarFuncionarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CriarFuncionarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Funcionario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Funcionario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ExisteContaEmailCompletedEventHandler(object sender, ExisteContaEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteContaEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExisteContaEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Conta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Conta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AlterarSenhaContaCompletedEventHandler(object sender, AlterarSenhaContaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlterarSenhaContaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlterarSenhaContaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Senha Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Senha)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AceitarTermosCompletedEventHandler(object sender, AceitarTermosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AceitarTermosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AceitarTermosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InserirPerguntaCompletedEventHandler(object sender, InserirPerguntaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InserirPerguntaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InserirPerguntaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AlterarPerguntaCompletedEventHandler(object sender, AlterarPerguntaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlterarPerguntaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlterarPerguntaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ResetaSenhaCompletedEventHandler(object sender, ResetaSenhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetaSenhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetaSenhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AlteraSenhaCompletedEventHandler(object sender, AlteraSenhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlteraSenhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlteraSenhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ValidaUsuarioCompletedEventHandler(object sender, ValidaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591